apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: my-app
  template:
    metadata:
      labels:
        name: my-app
    spec:
      containers:
      - name: my-image
        image: marbdevops/my-app:lts
        ports:
        - containerPort: 80
          targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  selector:
    name: my-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080

     
      
